name: CI

on: [push]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: install-tools
      run: |
        dotnet tool install --global Arbor.Tooler.GlobalTool
        dotnet tool install --global Arbor.Build.Bootstrapper
    - name: build
      env:
        Arbor.X.NuGet.PackageUpload.Server.ApiKey: ${{ secrets.myget }}
        Arbor.X.NuGet.PackageUpload.Server.Uri: "https://www.myget.org/F/milou-se/api/v2/package"
        Arbor.X.NuGet.PackageUpload.Enabled: "true"
        Arbor.X.NuGet.PackageUpload.ForceUploadEnabled: "true"
      run: build\build.bat